on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: upload release to PyPI
    environment: release
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3

      - name: Install Dependencies
        run: pdm install

      - name: Run Tests
        run: pytest --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Publish package distributions to PyPI
        run: pdm publish
